# Generated by Django 3.2.3 on 2021-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_books_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(related_name='books_liked', to='favourite_books_app.User'),
        ),
    ]
